-- #1 WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMER
SELECT gender, SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY gender;
-- #2 WHICH CUSTOMER USED DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
--#3 WHICH ARE THE TOP 5 PRODUCTSWITH THE HIGHEST AVERAGE REVIEW RATING
SELECT TOP 5 item_purchased,
ROUND(AVG(review_rating),2) AS AVERAGE_RATING
FROM customer
GROUP BY item_purchased
ORDER BY AVERAGE_RATING DESC
--#4 COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
--#5 DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBED AND NON SUBSCRIBED
SELECT subscription_status,
COUNT(customer_id) AS TOTAL_CUSTOMER,
AVG(purchase_amount) AS AVG_SPEND,
ROUND(SUM(purchase_amount),2) AS TOTAL_REVENUE
FROM customer
GROUP BY subscription_status
ORDER BY TOTAL_REVENUE,AVG_SPEND DESC

--#6 WHICH 5 PRODUCTSHAVE THE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNTS APPLIED?
SELECT TOP 5
item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT (*),2) AS DISCOUNT_RATE
FROM customer
GROUP BY item_purchased
ORDER BY DISCOUNT_RATE

--#7 SEGMENT CUSTOMERS INTO NEW , RETURNING AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES, AND SHOW THE COUNT OF EACH SEGMENT
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS [Number Of Customers]
FROM customer_type
GROUP BY customer_segment;

--#8 what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS TOTAL_ORDERS,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    TOTAL_ORDERS
FROM item_counts
WHERE item_rank <= 3;
--#9 ARE CUSTOMERSWHO ARE REPEAT BUYERS(MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?
SELECT subscription_status,
COUNT(customer_id) AS REPEAT_BUYERS
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status
--#10 WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP?
SELECT age_group,
SUM(purchase_amount) AS TOTAL_REVENUE
FROM customer
GROUP BY age_group
ORDER BY TOTAL_REVENUE DESC